apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJkbVJ2ZG1sdWIzWTZaMmh3WHpVMVFuUjBUVTVUVHpCUWVFMUhka2hNV1VSaFJHdFJjMGhVYVVsQmNUQTBUVEZrZEE9PSIKCQkJfQoJCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4Igp9
type: kubernetes.io/dockerconfigjson
